baseurl = "https://www.ship84.com/"
title = "Sea Scouts BSA Ship 84"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-147227489-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 1

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "Vessels"
    url  = "/resolution/"
    weight = 3

[[menu.main]]
    name = "Forms / Links"
    url  = "/forms/"
    weight = 5

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 6
    
[[menu.main]]
    name = "Donation"
    identifier = "donation"
    url  = "/Donation"
    weight = 7

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 8

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "http://facebook.com/ship84"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = ""
    defaultKeywords = ["Sea Scouts", "Ship 84", "Sailing", "BSA"]
    defaultDescription = "Sea Scouts BSA Ship 84 Southport CT"

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey ='testme'
    #googleMapsApiKey = process.env.API_KEY

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "ship84sailing@gmail.com"

    about_us = "<p>Leadership and seamanship skills through fun-filled programs at sea.</p>"
    copyright = "Copyright (c) 2019 - 2020, Ship 84; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2019"

    logo = "img/logo.png"
    address = """<p><strong>Skipper Erol Eyikan</strong>
        <br>Ship 84 - The Resolution
        <br>Ye Yacht Yard
        <br>985 Harbor Road
        <br>Southport, CT  06890
      </p>
      """
    latitude = "41.2178645"
    longitude = "-73.3824359"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us at ship84sailing@gmail.com</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many scouts and here is what some parents have had to say."

[params.see_more]
    enable = true
    icon = "fa fa-facebook"
    title = "Do you want to find out more about Ship 84?"
    subtitle = "Check out our Facebook page."
    link_url = "https://facebook.com/ship84"
    link_text = "Check out our Facebook page"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Other Resources"
    subtitle = "Click images to follow link"

[params.recent_posts]
    enable = false
    title = "Ship 84 Blog"
    subtitle = "Ship 84 is a Sea Scouts BSA ship in Southport Connecticut open to boys and girls from 14 to 21 years of age."

